---
engines:
  csslint:
    enabled: true
    exclude_fingerprints:
    - be0ea57f1c8997e06b960507a618cdcb
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - tests/
