language: php
sudo: false

php:
    - 5.6
    - 7.0
    - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - composer self-update
    - composer validate

install: composer install --dev

script: phpunit --coverage-clover=coverage.clover

after_script: wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
